services:
  admin-prod:
    container_name: aldorar-admin-prod
    image: aldorar-admin:prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "4200:4200"
    environment:
      NODE_ENV: production
    restart: always

  admin-dev:
    container_name: aldorar-admin-dev
    image: aldorar-admin:dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4300:4300"
    environment:
      NODE_ENV: development
    restart: always
